version: "3.0"
services:
  scraper:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    network_mode: host
    volumes: 
      - './app:/app'
    environment:
      MODE: 'DOCKER_DEVEL'
    command:
      python3 main.py



